### ISSUE TITLE
`bench_cg.py` fails with NVRTC Error

### ISSUE THREAD

**Issue by tvandera** [arrayfire/arrayfire-python#199]
Running bench_cg. py from the examples, gives me this error:

```
python bench_cg.py
ArrayFire v3.6.2 (CUDA, 64-bit Linux, build dc38ef1)
Platform: CUDA Toolkit 10, Driver: 410.79
[0] Tesla K80, 11442 MB, CUDA Compute 3.7
-1- Tesla K80, 11442 MB, CUDA Compute 3.7
-2- Tesla K80, 11442 MB, CUDA Compute 3.7
-3- Tesla K80, 11442 MB, CUDA Compute 3.7

Testing benchmark functions...
Traceback (most recent call last):
  File "bench_cg.py", line 197, in <module>
    test()
  File "bench_cg.py", line 144, in test
    if af.sum(af.abs(x1 - x2)/x2 > 1e-6):
  File "/home/vanderaa/miniconda3/envs/arrayfire/lib/python3.7/site-packages/arrayfire/array.py", line 894, in __truediv__
    return _binary_func(self, other, backend.get().af_div)
  File "/home/vanderaa/miniconda3/envs/arrayfire/lib/python3.7/site-packages/arrayfire/array.py", line 175, in _binary_func
    safe_call(c_func(c_pointer(out.arr), lhs.arr, other.arr, _bcast_var.get()))
  File "/home/vanderaa/miniconda3/envs/arrayfire/lib/python3.7/site-packages/arrayfire/util.py", line 79, in safe_call
    raise RuntimeError(to_str(err_str))
RuntimeError: In function std::vector<char> cuda::compileToPTX(const char*, std::string)
In file src/backend/cuda/jit.cpp:298
NVRTC Error(6): NVRTC_ERROR_COMPILATION
```

System: Linux K80 4.15.0-1035-azure #36~16.04.1-Ubuntu SMP Fri Nov 30 15:25:49 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
python --version: 
Python 3.7.1
```
$pip  show arrayfire
Name: arrayfire
Version: 3.6.20181017
Summary: Python bindings for ArrayFire
Home-page: http://arrayfire.com
Author: Pavan Yalamanchili
Author-email: contact@pavanky.com
License: BSD
Location: /mnt/vanderaa/miniconda3/envs/arrayfire/lib/python3.7/site-packages
Requires:
Required-by:
```

**Comment by pavanky** [comment]
@umar456 I thought this was fixed on 3.6 ?

**Comment by umar456** [comment]
Yeah, thats what I thought. I haven't looked at this yet. Will get to it later today.

**Comment by tvandera** [comment]
Hi Guys,

I have the same issue in some of my own codes. How do I at least get a more meaningful error message, such that I know that the code to be JITed it too big??

thanks,
Tom
