### ISSUE TITLE
Error in plot3d.py example

### ISSUE THREAD

**Issue by D-K-E** [arrayfire/arrayfire-python#205]
Hi,
I recently installed arrayfire python bindings. It passes all the tests and it launches few of the examples. However I got the following error when I tried to launch `plot3d.py` in the `examples/graphics` folder. Any idea ?

```python
ArrayFire v3.6.2 (CUDA, 64-bit Linux, build dc38ef1)
Platform: CUDA Toolkit 10, Driver: 418.39
[0] Quadro M2000M, 4044 MB, CUDA Compute 5.0
Traceback (most recent call last):
  File "examples/graphics/plot3.py", line 32, in <module>
    win.plot3(Pts)
  File "/home/user1/miniconda3/envs/ptmviewer/lib/python3.7/site-packages/arrayfire-3.6.20181017-py3.7.egg/arrayfire/graphics.py", line 296, in plot3
    assert(line.numdims() == 3)
AttributeError: 'NoneType' object has no attribute 'numdims'
```

**Comment by 9prady9** [comment]
From the error, it seems like `line` is not an ArrayFire array. Otherwise, it would have the numdims member function.
