### ISSUE TITLE
Error when using af.af.lapack.norm

### ISSUE THREAD

**Issue by Linuxboy2007** [arrayfire/arrayfire-python#216]
When I try to compute norm of matrix (vector) I got error:
`ArrayFire v3.6.4 (CUDA, 64-bit Linux, build 1b8030c)`
`Platform: CUDA Toolkit 10.0, Driver: 418.87.00`
`[0] GeForce GTX TITAN, 6081 MB, CUDA Compute 3.5`
`(100, 100)`
`Traceback (most recent call last):`
 ` File "/home/linuxboy/PycharmProjects/test/main.py", line 8, in <module>`
   ` nrma = af.lapack.norm(dA,norm_type = af.NORM.MATRIX_INF)`
  `File "/home/linuxboy/PycharmProjects/test/venv/lib/python3.7/site-packages/arrayfire/lapack.py", line 341, in norm`
   ` c_double_t(p), c_double_t(q)))`
  `File "/home/linuxboy/PycharmProjects/test/venv/lib/python3.7/site-packages/arrayfire/util.py", line 79, in safe_call`
    `raise RuntimeError(to_str(err_str))`
`RuntimeError: In function cuda::Kernel cuda::buildKernel(int, const string&, const string&, const std::vector<std::basic_string<char> >&, bool)
In file src/backend/cuda/nvrtc/cache.cpp:`
Cuda examples working, other af functions, for example, det, lu, matmul working good. Example bench_blas.py working.
I've got Ubuntu 19.04, ArrayFire 3.6.4, CudaToolkit 10.1.
`import arrayfire as af`
`af.set_backend('cuda')`
`af.info()`
`dA = af.randn(100,100,1,1,af.Dtype.f64)`
`print(dA.shape)`
`nrma = af.lapack.norm(dA,af.NORM.MATRIX_INF)`
`print(nrma)`

**Comment by Linuxboy2007** [comment]
II solved the problem - I downgraded version of ArrayFire to 3.6.2.
