### ISSUE TITLE
RuntimeError: Could not load any ArrayFire libraries.

### ISSUE THREAD

**Issue by luckydog1996** [arrayfire/arrayfire-python#239]
Hi, I am using MACOS, I have 1. Download and install binaries 2. pip install arrayfire 3. export DYLD_LIBRARY_PATH=/opt/arrayfire/lib:$DYLD_LIBRARY_PATH

It can be used with command line
<img width="720" alt="Screenshot 2020-10-15 at 08 29 41" src="https://user-images.githubusercontent.com/53863992/96059437-94ecf900-0ec0-11eb-8f4b-1302156e91d5.png">

But when I go to vscode and using the same conda environment, it shows 
```
Traceback (most recent call last):
  File "/Users/zetao/Documents/code/edu/python_code/first_try/VEM_deblur.py", line 3, in <module>
    import arrayfire as af 
  File "/Users/zetao/opt/anaconda3/lib/python3.7/site-packages/arrayfire/__init__.py", line 56, in <module>
    from .library    import *
  File "/Users/zetao/opt/anaconda3/lib/python3.7/site-packages/arrayfire/library.py", line 643, in <module>
    backend = _clibrary()
  File "/Users/zetao/opt/anaconda3/lib/python3.7/site-packages/arrayfire/library.py", line 619, in __init__
    raise RuntimeError("Could not load any ArrayFire libraries.\n" + more_info_str)
RuntimeError: Could not load any ArrayFire libraries.
```
Can anyone kindly explain why?

**Comment by pavanky** [comment]
Conda usually includes its own set of C++ and CUDA libraries which maybe different from your system ones. Perhaps arrayfire works with the system libs but not the Conda ones. Try running `os.system(/path/to/libafcuda.so)` and / or other arrayfire libraries.

**Comment by fuomag9** [comment]
Same issue here, I've tried everything but it won't load them

**Comment by roaffix** [comment]
Try to extend `LD_LIBRARY_PATH` with path to ArrayFire library (`.sh` setup file installs it to `/home/user/Downloads/arrayfire`). Worked for me

**Comment by SujithChristopher** [comment]
Same issue here.
