### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd5 in position 120: invalid continuation byte

### ISSUE THREAD

**Issue by JackyChan97** [arrayfire/arrayfire-python#249]
when using the function af.load_image() there was an error.

Traceback (most recent call last):
  File "VEM.py", line 847, in <module>
    uniform_dataset_eval(data_dir)
  File "VEM.py", line 761, in uniform_dataset_eval
    img, kernel = EM_Alg(l, 60, 19)
  File "VEM.py", line 512, in EM_Alg
    blur_img = af.image.load_image(data_dir + fn, is_color=False)
  File "D:\anaconda\envs\open-mmlab3.7\lib\site-packages\arrayfire\image.py", line 63, in load_image
    c_char_ptr_t(file_name.encode('ascii')), is_color))
  File "D:\anaconda\envs\open-mmlab3.7\lib\site-packages\arrayfire\util.py", line 81, in safe_call
    raise RuntimeError(to_str(err_str))
  File "D:\anaconda\envs\open-mmlab3.7\lib\site-packages\arrayfire\util.py", line 74, in to_str
    return str(c_str.value.decode('utf-8'))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd5 in position 120: invalid continuation byte

**Comment by JackyChan97** [comment]
I changed the system language to English, and the problem was solved
