### ISSUE TITLE
Error running fractal example

### ISSUE THREAD

**Issue by fpierfed** [arrayfire/arrayfire-python#88]
Hi there,

I have built the latest devel git branch of arrayfire and arrayfire-python on Mac OS X 10.11.5 using clang/llvm 7.3.0 mkl 2016.3.170 and coda 7.5. I am using Python 3.5.

I get the following error from fractal.py:

```
~/t/arrayfire-python/examples/graphics ±devel » python3.5 fractal.py
ArrayFire v3.4.0 (CUDA, 64-bit Mac OSX, build 072d507)
Platform: CUDA Toolkit 7.5, Driver: CUDA Driver Version: 7050
[0] GeForce GT 750M, 2048 MB, CUDA Compute 3.0
ArrayFire Fractal Demo

Iteration: 10 zoom: 100
277972, 99
LOG:
(): Error: Formal parameter space overflowed (4096 bytes max) in function KER13620677277748379544

target datalayout = "e-p:64:64:64-i1:8:8-i8:8:8-i16:16:16-i32:32:32-i64:64:64-f32:32:32-f64:64:64-v16:16:16-v32:32:32-v64:64:64-v128:128:128-n16:32:64"


target triple = "nvptx64-unknown-cuda"

[ BODY TOO LARGE]

Traceback (most recent call last):
  File "fractal.py", line 74, in <module>
    win.image(normalize(mag))
  File "fractal.py", line 46, in normalize
    mx = af.max(a)
  File "/Users/fpierfed/Library/Python/3.5/lib/python/site-packages/arrayfire-3.4.0-py3.5.egg/arrayfire/algorithm.py", line 149, in max
    return _reduce_all(a, backend.get().af_max_all)
  File "/Users/fpierfed/Library/Python/3.5/lib/python/site-packages/arrayfire-3.4.0-py3.5.egg/arrayfire/algorithm.py", line 26, in _reduce_all
    safe_call(c_func(ct.pointer(real), ct.pointer(imag), a.arr))
  File "/Users/fpierfed/Library/Python/3.5/lib/python/site-packages/arrayfire-3.4.0-py3.5.egg/arrayfire/util.py", line 79, in safe_call
    raise RuntimeError(to_str(err_str))
RuntimeError: In function irToPtx
In file src/backend/cuda/jit.cpp:300
NVVM Error (9): Failed to compile program
```

I should also add that my card is a GeForce 750M with 2GB of memory on a MacBook Pro.

**Comment by pavanky** [comment]
This has been fixed upstream in arrayfire 3.4.0 release.
